version: '3.8'
services:
  app:
    container_name: deno_fresh_app
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - deno_cache:/deno-dir
    environment:
      DENO_DIR: /deno-dir

volumes:
  deno_cache:
